site_name: InfoWorks

nav:
  - Home: index.md
  - SCRUM: 
    - User Story: SCRUM/userStory.md
    - Product Backlog: SCRUM/productBacklog.md
  - UML:
    - Casos e Usos: UML/casosUsos.md

theme:
  name: null
  custom_dir: 'cinder'
  language: pt
  favicon: imagem/favicon.ico
  logo: ./imagem/logo-correios.png