site_name: InfoWorks

repo_name: "2020.1-Correios"
repo_url: "https://github.com/Requisitos-de-Software/2020.1-Correios"

nav:
  - Home: index.md
  - SCRUM: 
    - User Story: SCRUM/userStory.md
    - Product Backlog: SCRUM/productBacklog.md
  - UML:
    - Casos e Usos: UML/casosUsos.md

theme:
  name: null
  custom_dir: 'cinder'
  language: pt
  logo: ./images/logo.png
  favicon: ./images/favicon.png
  palette:
    primary: blue